### ISSUE TITLE
copy你的代码，然后改了密钥，运行后访问了chatTest。报错500Internal Server Error.可以给我点修改意见吗

### ISSUE THREAD

**Issue by weideliti** [asleepyfish/chatgpt-demo#1]
copy你的代码，然后改了密钥，运行后访问了chatTest。报错500Internal Server Error.可以给我点修改意见吗

**Comment by asleepyfish** [comment]
> copy你的代码，然后改了密钥，运行后访问了chatTest。报错500Internal Server Error.可以给我点修改意见吗

把chatgpt版本更新到1.1.1试一试

**Comment by weideliti** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月12日(星期天) 晚上6:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [asleepyfish/chatgpt-demo] copy你的代码，然后改了密钥，运行后访问了chatTest。报错500Internal Server Error.可以给我点修改意见吗 (Issue #1)





  
copy你的代码，然后改了密钥，运行后访问了chatTest。报错500Internal Server Error.可以给我点修改意见吗
  
把chatgpt版本更新到1.1.1试一试

**Comment by Never-Left** [comment]
包版本不冲突吗，我这里无法启动
