### ISSUE TITLE
java.net.ConnectException: Connection timed out: connect

### ISSUE THREAD

**Issue by Marc1314** [asleepyfish/chatgpt-demo#2]
我的VPN打开了，浏览器&postman访问也没问题,就是运行会超时，为啥呀，idea需要单独设置VPN嘛

**Comment by asleepyfish** [comment]
> 

你的vpn的代理的ip和端口号需要填写到配置文件的对应位置，代码运行的时候发送Http请求的时候使用你填写的代理去发送请求。
