### ISSUE TITLE
启动报错无法注入bean

### ISSUE THREAD

**Issue by xiayana** [asleepyfish/chatgpt-demo#3]
Error creating bean with name 'openAiUtils' defined in io.github.asleepyfish.config.ChatGPTAutoConfigure: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [io.github.asleepyfish.util.OpenAiUtils] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@63947c6b]

是不是引入了这个包就不能引入com.theokanning.openai-gpt3-java了？

**Comment by asleepyfish** [comment]
> Error creating bean with name 'openAiUtils' defined in io.github.asleepyfish.config.ChatGPTAutoConfigure: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [io.github.asleepyfish.util.OpenAiUtils] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@63947c6b]
> 
> 是不是引入了这个包就不能引入com.theokanning.openai-gpt3-java了？

pom里面引入我的chatgpt依赖以后无需再引入com.theokanning.openai-gpt3-java，已自动包含
