### ISSUE TITLE
请问这方法里面的连续对话的方式是通过服务器本地缓存去实现的吧？

### ISSUE THREAD

**Issue by xiayana** [asleepyfish/chatgpt-demo#4]
如果我部署了多台服务器的话，那么请求轮询的情况下，两台服务器对于同一个用户的上下文是无法共享的对吗？能否把聊天上下文自定义记录在redis中这样去实现多台服务器获取相同用户的上下文？

**Comment by asleepyfish** [comment]
> 相同

你可以把源码下载下来，根据你的需求二开
