### ISSUE TITLE
问大佬几个问题

### ISSUE THREAD

**Issue by codesstar** [asleepyfish/chatgpt-demo#5]
你好，感谢大佬，提供的包很好用，不过这里有几个问题想请教一下。
1是有没有限制返回内容大小的内容，好像官网提供的是可以限制返回内容的文字数量，不知大佬的包有没有
2是该包是否可以使用chatgpt4咧，如果可以的话，要做哪些修改

**Comment by asleepyfish** [comment]
> 你好，感谢大佬，提供的包很好用，不过这里有几个问题想请教一下。 1是有没有限制返回内容大小的内容，好像官网提供的是可以限制返回内容的文字数量，不知大佬的包有没有 2是该包是否可以使用chatgpt4咧，如果可以的话，要做哪些修改

1.用createStreamChatCompletion(ChatCompletionRequest chatCompletionRequest, OutputStream os)和createChatCompletion(ChatCompletionRequest chatCompletionRequest)，ChatCompletionRequest 和ChatCompletionRequest 类中有限制返回大小的maxTokens属性，但是需要注意最大tokens不能超过模型所能允许的最大范围。

2.可以使用gpt4，但是前提是你是plus会员用户，这个需要付费，且申请GPT4 API，然后在application.yml中将chatgpt.chat-model属性修改成gpt4或者gpt-4-32k。

**Comment by codesstar** [comment]
感谢大佬，明白了。另外还有个问题想请教一下，就是我看了底层的客户端连接用的是okhttp是吧，是用的同步连接吗，能否改成异步连接。不知道是我网络不好的问题还是，感觉一个请求得5～6s才能返回，但是用了closeablehtypasyncclient好像速度快了很多。想问下大佬有没有提高请求速度的方法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: asleepyfish ***@***.***&gt;
发送时间: 2023年5月20日 14:48
收件人: asleepyfish/chatgpt-demo ***@***.***&gt;
抄送: codesstar ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5)





  
你好，感谢大佬，提供的包很好用，不过这里有几个问题想请教一下。 1是有没有限制返回内容大小的内容，好像官网提供的是可以限制返回内容的文字数量，不知大佬的包有没有 2是该包是否可以使用chatgpt4咧，如果可以的话，要做哪些修改
  
1.用createStreamChatCompletion(ChatCompletionRequest chatCompletionRequest, OutputStream os)和createChatCompletion(ChatCompletionRequest chatCompletionRequest)，ChatCompletionRequest 和ChatCompletionRequest 类中有限制返回大小的maxTokens属性，但是需要注意最大tokens不能超过模型所能允许的最大范围。
 
2.可以使用gpt4，但是前提是你是plus会员用户，这个需要付费，且申请GPT4 API，然后在application.yml中将chatgpt.chat-model属性修改成gpt4或者gpt-4-32k。

**Comment by asleepyfish** [comment]
> 感谢大佬，明白了。另外还有个问题想请教一下，就是我看了底层的客户端连接用的是okhttp是吧，是用的同步连接吗，能否改成异步连接。不知道是我网络不好的问题还是，感觉一个请求得5～6s才能返回，但是用了closeablehtypasyncclient好像速度快了很多。想问下大佬有没有提高请求速度的方法 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: asleepyfish ***@***.***&gt; 发送时间: 2023年5月20日 14:48 收件人: asleepyfish/chatgpt-demo ***@***.***&gt; 抄送: codesstar ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5) 你好，感谢大佬，提供的包很好用，不过这里有几个问题想请教一下。 1是有没有限制返回内容大小的内容，好像官网提供的是可以限制返回内容的文字数量，不知大佬的包有没有 2是该包是否可以使用chatgpt4咧，如果可以的话，要做哪些修改 1.用createStreamChatCompletion(ChatCompletionRequest chatCompletionRequest, OutputStream os)和createChatCompletion(ChatCompletionRequest chatCompletionRequest)，ChatCompletionRequest 和ChatCompletionRequest 类中有限制返回大小的maxTokens属性，但是需要注意最大tokens不能超过模型所能允许的最大范围。 2.可以使用gpt4，但是前提是你是plus会员用户，这个需要付费，且申请GPT4 API，然后在application.yml中将chatgpt.chat-model属性修改成gpt4或者gpt-4-32k。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

数据是同步建立HTTP连接传输的，异步收不到数据。用流式聊天的接口，会秒返回数据，并流式打印出来。

**Comment by codesstar** [comment]
哦哦明白了 那可以问个问题吗 类似于chatgpt官网的那种打字机效果 是通过流式输出还是说它是先获取内容再打印出来。也就是说反应快，是因为是流式输出是吧，我直接调用chat接口获取内容的速度其实和streamchat全部输出的速度是一样的。只不过一个有及时反馈，一个没有，可以这么理解不。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: asleepyfish ***@***.***&gt;
发送时间: 2023年5月22日 14:19
收件人: asleepyfish/chatgpt-demo ***@***.***&gt;
抄送: codesstar ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5)





  
感谢大佬，明白了。另外还有个问题想请教一下，就是我看了底层的客户端连接用的是okhttp是吧，是用的同步连接吗，能否改成异步连接。不知道是我网络不好的问题还是，感觉一个请求得5～6s才能返回，但是用了closeablehtypasyncclient好像速度快了很多。想问下大佬有没有提高请求速度的方法 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: asleepyfish @.&gt; 发送时间: 2023年5月20日 14:48 收件人: asleepyfish/chatgpt-demo @.&gt; 抄送: codesstar @.&gt;, Author @.&gt; 主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5) 你好，感谢大佬，提供的包很好用，不过这里有几个问题想请教一下。 1是有没有限制返回内容大小的内容，好像官网提供的是可以限制返回内容的文字数量，不知大佬的包有没有 2是该包是否可以使用chatgpt4咧，如果可以的话，要做哪些修改 1.用createStreamChatCompletion(ChatCompletionRequest chatCompletionRequest, OutputStream os)和createChatCompletion(ChatCompletionRequest chatCompletionRequest)，ChatCompletionRequest 和ChatCompletionRequest 类中有限制返回大小的maxTokens属性，但是需要注意最大tokens不能超过模型所能允许的最大范围。 2.可以使用gpt4，但是前提是你是plus会员用户，这个需要付费，且申请GPT4 API，然后在application.yml中将chatgpt.chat-model属性修改成gpt4或者gpt-4-32k。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
数据是同步建立HTTP连接传输的，异步收不到数据。用流式聊天的接口，会秒返回数据，并流式打印出来。

**Comment by asleepyfish** [comment]
> 哦哦明白了 那可以问个问题吗 类似于chatgpt官网的那种打字机效果 是通过流式输出还是说它是先获取内容再打印出来。也就是说反应快，是因为是流式输出是吧，我直接调用chat接口获取内容的速度其实和streamchat全部输出的速度是一样的。只不过一个有及时反馈，一个没有，可以这么理解不。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: asleepyfish ***@***.***&gt; 发送时间: 2023年5月22日 14:19 收件人: asleepyfish/chatgpt-demo ***@***.***&gt; 抄送: codesstar ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5) 感谢大佬，明白了。另外还有个问题想请教一下，就是我看了底层的客户端连接用的是okhttp是吧，是用的同步连接吗，能否改成异步连接。不知道是我网络不好的问题还是，感觉一个请求得5～6s才能返回，但是用了closeablehtypasyncclient好像速度快了很多。想问下大佬有没有提高请求速度的方法 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: asleepyfish @.&gt; 发送时间: 2023年5月20日 14:48 收件人: asleepyfish/chatgpt-demo @.&gt; 抄送: codesstar @.&gt;, Author @.&gt; 主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5) 你好，感谢大佬，提供的包很好用，不过这里有几个问题想请教一下。 1是有没有限制返回内容大小的内容，好像官网提供的是可以限制返回内容的文字数量，不知大佬的包有没有 2是该包是否可以使用chatgpt4咧，如果可以的话，要做哪些修改 1.用createStreamChatCompletion(ChatCompletionRequest chatCompletionRequest, OutputStream os)和createChatCompletion(ChatCompletionRequest chatCompletionRequest)，ChatCompletionRequest 和ChatCompletionRequest 类中有限制返回大小的maxTokens属性，但是需要注意最大tokens不能超过模型所能允许的最大范围。 2.可以使用gpt4，但是前提是你是plus会员用户，这个需要付费，且申请GPT4 API，然后在application.yml中将chatgpt.chat-model属性修改成gpt4或者gpt-4-32k。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 数据是同步建立HTTP连接传输的，异步收不到数据。用流式聊天的接口，会秒返回数据，并流式打印出来。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没有马上流式输出的原因是因为你前端请求不是流式的，是组件问题，看我博客里有流式的demo

**Comment by codesstar** [comment]
好的 感谢！我去看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: asleepyfish ***@***.***&gt;
发送时间: 2023年5月22日 14:43
收件人: asleepyfish/chatgpt-demo ***@***.***&gt;
抄送: codesstar ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5)





  
哦哦明白了 那可以问个问题吗 类似于chatgpt官网的那种打字机效果 是通过流式输出还是说它是先获取内容再打印出来。也就是说反应快，是因为是流式输出是吧，我直接调用chat接口获取内容的速度其实和streamchat全部输出的速度是一样的。只不过一个有及时反馈，一个没有，可以这么理解不。 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: asleepyfish @.&gt; 发送时间: 2023年5月22日 14:19 收件人: asleepyfish/chatgpt-demo @.&gt; 抄送: codesstar @.&gt;, Author @.&gt; 主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5) 感谢大佬，明白了。另外还有个问题想请教一下，就是我看了底层的客户端连接用的是okhttp是吧，是用的同步连接吗，能否改成异步连接。不知道是我网络不好的问题还是，感觉一个请求得5～6s才能返回，但是用了closeablehtypasyncclient好像速度快了很多。想问下大佬有没有提高请求速度的方法 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: asleepyfish @.&gt; 发送时间: 2023年5月20日 14:48 收件人: asleepyfish/chatgpt-demo @.&gt; 抄送: codesstar @.&gt;, Author @.&gt; 主题: Re: [asleepyfish/chatgpt-demo] 问大佬几个问题 (Issue #5) 你好，感谢大佬，提供的包很好用，不过这里有几个问题想请教一下。 1是有没有限制返回内容大小的内容，好像官网提供的是可以限制返回内容的文字数量，不知大佬的包有没有 2是该包是否可以使用chatgpt4咧，如果可以的话，要做哪些修改 1.用createStreamChatCompletion(ChatCompletionRequest chatCompletionRequest, OutputStream os)和createChatCompletion(ChatCompletionRequest chatCompletionRequest)，ChatCompletionRequest 和ChatCompletionRequest 类中有限制返回大小的maxTokens属性，但是需要注意最大tokens不能超过模型所能允许的最大范围。 2.可以使用gpt4，但是前提是你是plus会员用户，这个需要付费，且申请GPT4 API，然后在application.yml中将chatgpt.chat-model属性修改成gpt4或者gpt-4-32k。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 数据是同步建立HTTP连接传输的，异步收不到数据。用流式聊天的接口，会秒返回数据，并流式打印出来。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
没有马上流式输出的原因是因为你前端请求不是流式的，是组件问题，看我博客里有流式的demo
